#!/bin/bash

# Okay, so it's a bash script. You should probably add some stuff.

echo 'We ought to start from a clean slate.'
sudo yum update -y

echo 'Now we should install some important stuff'

# mongodb and related utils

dnf install robomongo mongodb-server -y

# editors

dnf install atom -y

# gis

dnf install qgis grass gdal -y

# design

dnf install gimp inkscape ImageMagick graphviz blender dia -y

# media

dnf install ffmpeg vlc

# dev

dnf install scipy python-autopep8 gcc-c++ arduino -y

# terminal

dnf install tmux htop vim -y

# misc

dnf install calibre dosbox xchat -y
